// Maps colloquial Indian-language commodity names to AGMARKNET canonical English names.
// Used by search to make "tamatar" → "Tomato" work for non-English users.
// Extend liberally — every alias adds usability.

export const COMMODITY_ALIASES: Record<string, string> = {
  // Hindi
  tamatar: "Tomato",
  pyaaz: "Onion",
  pyaz: "Onion",
  aloo: "Potato",
  alu: "Potato",
  gobhi: "Cauliflower",
  phoolgobhi: "Cauliflower",
  patta: "Cabbage",
  bandgobhi: "Cabbage",
  bhindi: "Bhindi(Ladies Finger)",
  bhendi: "Bhindi(Ladies Finger)",
  baingan: "Brinjal",
  begun: "Brinjal",
  matar: "Green Peas",
  hari_mirch: "Green Chilli",
  mirchi: "Green Chilli",
  adrak: "Ginger(Green)",
  lehsun: "Garlic",
  haldi: "Turmeric",
  dhaniya: "Coriander(Leaves)",
  pudina: "Mint(Pudina)",
  methi: "Methi(Leaves)",
  palak: "Spinach",
  gajar: "Carrot",
  shimla_mirch: "Capsicum",
  kheera: "Cucumbar(Kheera)",
  kakdi: "Cucumbar(Kheera)",
  khira: "Cucumbar(Kheera)",
  lauki: "Bottle gourd",
  ghiya: "Bottle gourd",
  tinda: "Tinda",
  arbi: "Arhar Dal(Tur Dal)",
  arhar: "Arhar (Tur/Red Gram)(Whole)",
  tur: "Arhar (Tur/Red Gram)(Whole)",
  moong: "Green Gram (Moong)(Whole)",
  urad: "Black Gram (Urd Beans)(Whole)",
  masoor: "Lentil (Masur)(Whole)",
  chana: "Bengal Gram(Gram)(Whole)",
  rajma: "Rajma",
  soya: "Soyabean",
  soyabean: "Soyabean",
  sarso: "Mustard",
  sarson: "Mustard",
  til: "Sesamum",
  gehu: "Wheat",
  gehun: "Wheat",
  chawal: "Paddy(Dhan)(Common)",
  dhan: "Paddy(Dhan)(Common)",
  makka: "Maize",
  bajra: "Bajra(Pearl Millet/Cumbu)",
  jowar: "Jowar(Sorghum)",
  ragi: "Ragi (Finger Millet)",
  ganna: "Sugar",
  ikhh: "Sugar",
  kapas: "Cotton",
  binola: "Cotton Seed",
  santra: "Orange",
  seb: "Apple",
  kela: "Banana - Green",
  aam: "Mango",
  anaar: "Pomegranate",
  papita: "Papaya",
  amrood: "Guava",
  angoor: "Grapes",
  nimbu: "Lemon",
  // Marathi
  kanda: "Onion",
  batata: "Potato",
  tomato: "Tomato",
  // Bengali
  alo: "Potato",
  begoon: "Brinjal",
  // Telugu / Tamil / Kannada (transliterations)
  ulli: "Onion",
  vengayam: "Onion",
  thakkali: "Tomato",
  urulai: "Potato",
  bangaladumpa: "Potato",
};

export function resolveAlias(query: string): string | null {
  const q = query.trim().toLowerCase().replace(/\s+/g, "_");
  return COMMODITY_ALIASES[q] ?? COMMODITY_ALIASES[q.replace(/_/g, "")] ?? null;
}
